"""The parley stack (spec: "AWS mapping").

    Internet ──HTTPS──▶ load balancer ──▶ API service (Fargate)   ┐
                                          worker service (Fargate) ├─▶ RDS PostgreSQL
                                          migrate task (run once)  ┘   (private subnets)

    SES receiving ──▶ S3 (raw mail) ──▶ forwarder Lambda ──▶ POST /v1/inbound/email

Both services run the same image (the repository's Dockerfile), the API with
its default command and the worker with `parley worker`. Each task also runs
the AWS Distro for OpenTelemetry collector, which sends traces to X-Ray
(CloudWatch > Traces). Logs go to CloudWatch Logs.

Secrets never appear in the template: the database password is generated by
RDS, the inbound-mail secret by Secrets Manager, and both reach the containers
as ECS secrets. The Twilio credentials live in a secret you create by hand.
"""

from pathlib import Path

from aws_cdk import (
    Annotations,
    CfnOutput,
    Duration,
    RemovalPolicy,
    Stack,
)
from aws_cdk import aws_certificatemanager as acm
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_ecs as ecs
from aws_cdk import aws_ecs_patterns as ecs_patterns
from aws_cdk import aws_iam as iam
from aws_cdk import aws_lambda as lambda_
from aws_cdk import aws_logs as logs
from aws_cdk import aws_rds as rds
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_notifications as s3n
from aws_cdk import aws_secretsmanager as secretsmanager
from aws_cdk import aws_ses as ses
from aws_cdk import aws_ses_actions as ses_actions
from aws_cdk import aws_sqs as sqs
from constructs import Construct

from infra.config import DeployConfig

REPO_ROOT = Path(__file__).resolve().parents[1]
FORWARDER_DIR = Path(__file__).resolve().parent / "forwarder"
OTEL_CONFIG = (REPO_ROOT / "docker" / "otel-collector-aws.yaml").read_text(encoding="utf-8")
# The app's default limit on a call (PARLEY_VOICE_MAX_SECONDS).
MAX_CALL_SECONDS = 420
OTEL_IMAGE = "public.ecr.aws/aws-observability/aws-otel-collector:v0.43.1"


class ParleyStack(Stack):
    def __init__(
        self, scope: Construct, construct_id: str, config: DeployConfig, **kwargs: object
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)  # type: ignore[arg-type]
        self.config = config

        # --- Network and database ------------------------------------------------
        vpc = ec2.Vpc(self, "Vpc", max_azs=2, nat_gateways=1)
        database = rds.DatabaseInstance(
            self,
            "Database",
            engine=rds.DatabaseInstanceEngine.postgres(version=rds.PostgresEngineVersion.VER_16),
            instance_type=ec2.InstanceType(config.db_instance_type),
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS),
            credentials=rds.Credentials.from_generated_secret("parley"),
            database_name="parley",
            allocated_storage=20,
            storage_encrypted=True,
            publicly_accessible=False,
            backup_retention=Duration.days(7),
            deletion_protection=config.keep_database,
            removal_policy=RemovalPolicy.SNAPSHOT
            if config.keep_database
            else RemovalPolicy.DESTROY,
        )
        assert database.secret is not None

        # --- Storage and secrets -------------------------------------------------------
        # Aging-report CSVs for CSV tenants: give the tenant s3://<bucket>/<key> paths.
        data_bucket = s3.Bucket(
            self,
            "DataBucket",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            enforce_ssl=True,
            versioned=True,
            removal_policy=RemovalPolicy.RETAIN,
        )
        app_secret = secretsmanager.Secret(
            self,
            "AppSecret",
            description="parley: the shared secret that signs inbound email posts",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template="{}",
                generate_string_key="inbound_secret",
                exclude_punctuation=True,
                password_length=48,
            ),
        )

        # --- What the containers may do ---------------------------------------------
        task_role = iam.Role(
            self, "TaskRole", assumed_by=iam.ServicePrincipal("ecs-tasks.amazonaws.com")
        )
        data_bucket.grant_read(task_role)
        task_role.add_to_policy(
            iam.PolicyStatement(
                sid="Models",
                actions=[
                    "bedrock:InvokeModel",
                    "bedrock:InvokeModelWithResponseStream",
                    "bedrock:InvokeModelWithBidirectionalStream",
                ],
                resources=["*"],
            )
        )
        task_role.add_to_policy(
            iam.PolicyStatement(
                sid="SendEmail", actions=["ses:SendEmail", "ses:SendRawEmail"], resources=["*"]
            )
        )
        task_role.add_to_policy(
            iam.PolicyStatement(
                sid="Traces",
                actions=["xray:PutTraceSegments", "xray:PutTelemetryRecords"],
                resources=["*"],
            )
        )
        # Adapter settings may name secrets as "aws:<arn>"; keep them under parley/.
        task_role.add_to_policy(
            iam.PolicyStatement(
                sid="AdapterSecrets",
                actions=["secretsmanager:GetSecretValue"],
                resources=[f"arn:aws:secretsmanager:{self.region}:{self.account}:secret:parley/*"],
            )
        )

        environment = self._environment()
        secrets = {
            "PARLEY_DATABASE_SECRET": ecs.Secret.from_secrets_manager(database.secret),
            "PARLEY_INBOUND_SECRET": ecs.Secret.from_secrets_manager(app_secret, "inbound_secret"),
        }
        if config.twilio:
            twilio = secretsmanager.Secret.from_secret_name_v2(
                self, "TwilioSecret", config.twilio_secret_name
            )
            secrets["PARLEY_TWILIO_ACCOUNT_SID"] = ecs.Secret.from_secrets_manager(
                twilio, "account_sid"
            )
            secrets["PARLEY_TWILIO_AUTH_TOKEN"] = ecs.Secret.from_secrets_manager(
                twilio, "auth_token"
            )
            secrets["PARLEY_TWILIO_FROM_NUMBER"] = ecs.Secret.from_secrets_manager(
                twilio, "from_number"
            )

        # --- Services --------------------------------------------------------------------
        cluster = ecs.Cluster(
            self, "Cluster", vpc=vpc, container_insights_v2=ecs.ContainerInsights.ENABLED
        )
        image = ecs.ContainerImage.from_asset(str(REPO_ROOT))
        log_group = logs.LogGroup(
            self,
            "Logs",
            retention=logs.RetentionDays.ONE_MONTH,
            removal_policy=RemovalPolicy.DESTROY,
        )

        certificate = (
            acm.Certificate.from_certificate_arn(self, "Certificate", config.certificate_arn)
            if config.certificate_arn
            else None
        )
        if certificate is None:
            Annotations.of(self).add_warning(
                "No certificate_arn: the API is served over plain HTTP. Fine for a test, "
                "not for real customer data, and Twilio needs HTTPS."
            )
        api = ecs_patterns.ApplicationLoadBalancedFargateService(
            self,
            "Api",
            cluster=cluster,
            cpu=512,
            memory_limit_mib=1024,
            desired_count=config.api_count,
            public_load_balancer=True,
            certificate=certificate,
            redirect_http=certificate is not None,
            # Calls keep a WebSocket open for minutes.
            idle_timeout=Duration.minutes(10),
            task_image_options=ecs_patterns.ApplicationLoadBalancedTaskImageOptions(
                image=image,
                container_name="api",
                container_port=8000,
                environment=environment,
                secrets=secrets,
                task_role=task_role,
                log_driver=ecs.LogDrivers.aws_logs(stream_prefix="api", log_group=log_group),
            ),
            circuit_breaker=ecs.DeploymentCircuitBreaker(rollback=True),
            # Start new tasks before stopping old ones; with the deregistration
            # delay below, calls in progress finish before their task stops.
            min_healthy_percent=100,
            max_healthy_percent=200,
        )
        api.target_group.configure_health_check(path="/healthz", healthy_http_codes="200")
        # When a deploy replaces a task, the load balancer stops sending it new
        # requests but lets open connections (a call's WebSocket) finish for this
        # long before the task is stopped: longer than the longest call.
        api.target_group.set_attribute(
            "deregistration_delay.timeout_seconds", str(MAX_CALL_SECONDS + 60)
        )
        self._add_collector(api.task_definition, log_group)

        worker_task = ecs.FargateTaskDefinition(
            self, "WorkerTask", cpu=512, memory_limit_mib=1024, task_role=task_role
        )
        worker_task.add_container(
            "worker",
            image=image,
            command=["parley", "worker"],
            environment=environment,
            secrets=secrets,
            logging=ecs.LogDrivers.aws_logs(stream_prefix="worker", log_group=log_group),
        )
        self._add_collector(worker_task, log_group)
        worker = ecs.FargateService(
            self,
            "Worker",
            cluster=cluster,
            task_definition=worker_task,
            desired_count=1,
            circuit_breaker=ecs.DeploymentCircuitBreaker(rollback=True),
            # Briefly two workers during a deploy: safe, since every step locks its rows.
            min_healthy_percent=100,
            max_healthy_percent=200,
        )

        # Migrations run as a one-off task after each deploy (see the output).
        migrate_task = ecs.FargateTaskDefinition(
            self, "MigrateTask", cpu=256, memory_limit_mib=512, task_role=task_role
        )
        migrate_task.add_container(
            "migrate",
            image=image,
            command=["alembic", "upgrade", "head"],
            environment=environment,
            secrets=secrets,
            logging=ecs.LogDrivers.aws_logs(stream_prefix="migrate", log_group=log_group),
        )
        migrate_group = ec2.SecurityGroup(self, "MigrateSecurityGroup", vpc=vpc)

        for peer in (api.service, worker):
            database.connections.allow_default_port_from(peer)
        database.connections.allow_default_port_from(migrate_group)

        # --- Email -------------------------------------------------------------------------
        if config.email_from:
            domain = config.email_from.partition("@")[2]  # checked in DeployConfig
            ses.EmailIdentity(self, "SenderDomain", identity=ses.Identity.domain(domain))
        if config.receive_email:
            self._receive_email(app_secret)

        # --- Outputs -----------------------------------------------------------------------
        url = config.public_url or f"http://{api.load_balancer.load_balancer_dns_name}"
        CfnOutput(self, "ApiUrl", value=url)
        CfnOutput(self, "LoadBalancerDns", value=api.load_balancer.load_balancer_dns_name)
        CfnOutput(self, "DataBucketName", value=data_bucket.bucket_name)
        subnets = ",".join(s.subnet_id for s in vpc.private_subnets)
        CfnOutput(
            self,
            "MigrateCommand",
            description="Run after every deploy that adds a migration",
            value=(
                f"aws ecs run-task --cluster {cluster.cluster_name} "
                f"--task-definition {migrate_task.task_definition_arn} --launch-type FARGATE "
                "--network-configuration 'awsvpcConfiguration={subnets=["
                + subnets
                + f"],securityGroups=[{migrate_group.security_group_id}]}}'"
            ),
        )
        CfnOutput(
            self,
            "CreateTenantCommand",
            description="Create a tenant (prints its API key and webhook secret in the task logs)",
            value=(
                f"aws ecs run-task --cluster {cluster.cluster_name} "
                f"--task-definition {migrate_task.task_definition_arn} --launch-type FARGATE "
                "--network-configuration 'awsvpcConfiguration={subnets=["
                + subnets
                + f"],securityGroups=[{migrate_group.security_group_id}]}}' "
                '--overrides \'{"containerOverrides":[{"name":"migrate","command":'
                '["parley","create-tenant","--name","<name>","--invoices-csv",'
                '"s3://<bucket>/<key>"]}]}\''
            ),
        )

    def _environment(self) -> dict[str, str]:
        config = self.config
        environment = {
            "PARLEY_AWS_REGION": self.region,
            "PARLEY_MODEL_PROVIDER": config.model_provider,
            "PARLEY_CHANNEL": "ses" if config.email_from else "dry_run",
            "PARLEY_TRACING": "otlp",
            "PARLEY_LOG_LEVEL": "INFO",
        }
        if config.email_from:
            environment["PARLEY_EMAIL_FROM"] = config.email_from
        if config.reply_domain:
            environment["PARLEY_REPLY_DOMAIN"] = config.reply_domain
        if config.public_url:
            environment["PARLEY_PUBLIC_URL"] = config.public_url
        if config.speech:
            environment["PARLEY_SPEECH_PROVIDER"] = "nova_sonic"
        if config.twilio:
            environment["PARLEY_VOICE"] = "twilio"
            environment["PARLEY_VOICE_ALLOWED_NUMBERS"] = ",".join(config.voice_allowed_numbers)
        return environment

    def _add_collector(self, task: ecs.TaskDefinition, log_group: logs.ILogGroup) -> None:
        """The ADOT collector beside the app: receives OTLP on localhost:4318 and
        sends traces to X-Ray. Not essential: if it stops, the app keeps running."""
        task.add_container(
            "otel-collector",
            image=ecs.ContainerImage.from_registry(OTEL_IMAGE),
            essential=False,
            environment={"AOT_CONFIG_CONTENT": OTEL_CONFIG},
            logging=ecs.LogDrivers.aws_logs(stream_prefix="otel", log_group=log_group),
            memory_reservation_mib=64,
        )

    def _receive_email(self, app_secret: secretsmanager.ISecret) -> None:
        """SES receiving for the reply domain: store each email in S3, then the
        forwarder Lambda posts it to the API, signed."""
        config = self.config
        inbox = s3.Bucket(
            self,
            "InboundMail",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            enforce_ssl=True,
            lifecycle_rules=[s3.LifecycleRule(expiration=Duration.days(30))],
            removal_policy=RemovalPolicy.RETAIN,
        )
        failed = sqs.Queue(self, "ForwarderDeadLetters", retention_period=Duration.days(14))
        forwarder = lambda_.Function(
            self,
            "MailForwarder",
            runtime=lambda_.Runtime.PYTHON_3_12,
            handler="handler.handler",
            code=lambda_.Code.from_asset(str(FORWARDER_DIR)),
            timeout=Duration.seconds(30),
            retry_attempts=2,
            dead_letter_queue=failed,
            environment={
                "INBOUND_URL": f"{config.public_url.rstrip('/')}/v1/inbound/email",
                "APP_SECRET_ARN": app_secret.secret_arn,
            },
        )
        inbox.grant_read(forwarder)
        app_secret.grant_read(forwarder)
        inbox.add_event_notification(
            s3.EventType.OBJECT_CREATED,
            s3n.LambdaDestination(forwarder),
            s3.NotificationKeyFilter(prefix="mail/"),
        )
        rule_set = ses.ReceiptRuleSet(self, "ReceiptRules")
        rule_set.add_rule(
            "ReplyDomain",
            recipients=[config.reply_domain],
            scan_enabled=True,
            actions=[ses_actions.S3(bucket=inbox, object_key_prefix="mail/")],
        )
        CfnOutput(
            self,
            "ActivateReceiptRules",
            description="SES uses one active rule set per region; activate this one once",
            value="aws ses set-active-receipt-rule-set --rule-set-name "
            + rule_set.receipt_rule_set_name,
        )
