"""M6: events in and webhooks out

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-03 03:38:34.161194
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_inbound_events_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_events")),
        sa.UniqueConstraint(
            "tenant_id", "event_id", name=op.f("uq_inbound_events_tenant_id_event_id")
        ),
    )
    op.create_index(
        op.f("ix_inbound_events_received_at"), "inbound_events", ["received_at"], unique=False
    )
    op.create_index(
        op.f("ix_inbound_events_tenant_id"), "inbound_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "outbound_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "delivered",
                "failed",
                name="webhookstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_outbound_events_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_events")),
        sa.UniqueConstraint("seq", name=op.f("uq_outbound_events_seq")),
    )
    op.create_index(
        "ix_outbound_events_due",
        "outbound_events",
        ["tenant_id", "status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbound_events_tenant_id"), "outbound_events", ["tenant_id"], unique=False
    )
    op.add_column("tenants", sa.Column("webhook_url", sa.String(length=500), nullable=True))
    # Existing tenants get a random secret: two random UUIDs as 64 hex characters.
    op.add_column("tenants", sa.Column("webhook_secret", sa.String(length=64), nullable=True))
    op.execute(
        "UPDATE tenants SET webhook_secret = replace(gen_random_uuid()::text || "
        "gen_random_uuid()::text, '-', '')"
    )
    op.alter_column("tenants", "webhook_secret", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "webhook_secret")
    op.drop_column("tenants", "webhook_url")
    op.drop_index(op.f("ix_outbound_events_tenant_id"), table_name="outbound_events")
    op.drop_index("ix_outbound_events_due", table_name="outbound_events")
    op.drop_table("outbound_events")
    op.drop_index(op.f("ix_inbound_events_tenant_id"), table_name="inbound_events")
    op.drop_index(op.f("ix_inbound_events_received_at"), table_name="inbound_events")
    op.drop_table("inbound_events")
    # ### end Alembic commands ###
