"""M7: voice calls

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-03 05:39:14.610855
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TASK_KINDS_V1 = ["escalation", "review_reply", "approve_send", "verify_payment", "review_dispute"]
TASK_KINDS_V2 = [*TASK_KINDS_V1, "review_call"]


def _quoted(values: list[str]) -> str:
    return ", ".join(f"'{v}'" for v in values)


def _task_kinds(values: list[str]) -> None:
    op.drop_constraint(op.f("ck_tasks_taskkind"), "tasks", type_="check")
    op.create_check_constraint(op.f("ck_tasks_taskkind"), "tasks", f"kind IN ({_quoted(values)})")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("provider_call_id", sa.String(length=100), nullable=True),
        sa.Column("to_number", sa.String(length=32), nullable=False),
        sa.Column("test", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "placed",
                "in_progress",
                "answered",
                "not_reached",
                name="callstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("answered_by", sa.String(length=32), nullable=True),
        sa.Column("identity_confirmed", sa.Boolean(), nullable=False),
        sa.Column("turns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "audit",
            sa.Enum(
                "passed",
                "failed",
                name="callaudit",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("audit_problems", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_calls_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_calls_message_id_messages")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_calls_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
        sa.UniqueConstraint("message_id", name=op.f("uq_calls_message_id")),
        sa.UniqueConstraint("token", name=op.f("uq_calls_token")),
    )
    op.create_index(op.f("ix_calls_customer_id"), "calls", ["customer_id"], unique=False)
    op.create_index(op.f("ix_calls_tenant_id"), "calls", ["tenant_id"], unique=False)
    op.add_column(
        "tenants", sa.Column("voice_transfer_number", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###
    _task_kinds(TASK_KINDS_V2)


def downgrade() -> None:
    _task_kinds(TASK_KINDS_V1)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "voice_transfer_number")
    op.drop_index(op.f("ix_calls_tenant_id"), table_name="calls")
    op.drop_index(op.f("ix_calls_customer_id"), table_name="calls")
    op.drop_table("calls")
    # ### end Alembic commands ###
