"""Write-back: notes about collection activity, to be added to invoices in the source

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-08 06:13:30.392047
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "written",
                "failed",
                name="notestatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("written_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_source_notes_invoice_id_invoices")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_source_notes_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_notes")),
        sa.UniqueConstraint("seq", name=op.f("uq_source_notes_seq")),
    )
    op.create_index(
        "ix_source_notes_due",
        "source_notes",
        ["tenant_id", "status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_notes_invoice_id"), "source_notes", ["invoice_id"], unique=False
    )
    op.create_index(op.f("ix_source_notes_tenant_id"), "source_notes", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_notes_tenant_id"), table_name="source_notes")
    op.drop_index(op.f("ix_source_notes_invoice_id"), table_name="source_notes")
    op.drop_index("ix_source_notes_due", table_name="source_notes")
    op.drop_table("source_notes")
    # ### end Alembic commands ###
